### ISSUE TITLE
How should we separate documents to file from documents to mail on download screen?

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-HousingCodeChecklist#182]
This is the current look, which is pretty messy (especially with the send button):

![image](https://user-images.githubusercontent.com/7645641/188482465-7bfc8cea-4219-43d2-966c-80d9e3535dc0.png)

Do we need to distinguish between the two types of files? Will the user instructions be enough?

Possible choices:

1. Use headings to group the two different sections
2. Use a single download list, with a bundled set of instructions and files for each type of document (print and mail vs file)
3. Multiple versions of the same files to handle different user needs?

This is something we thought a lot about in Washington State Parenting Plan, DVPO and SAPO forms. Laurie had good ideas about how to group documents, but some of that was limited by what LHI can do. 

https://www.washingtonlawhelp.org/resource/parenting-plan-forms-online

**Comment by miabonardi** [comment]
This is done and looks really good now

![Screen Shot 2023-08-03 at 2 53 19 PM](https://github.com/LemmaLegalConsulting/docassemble-HousingCodeChecklist/assets/65858862/8603f7db-4941-43c0-9790-7058c0a255e5)
