### ISSUE TITLE
Allow two addresses for tenants?

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-HousingCodeChecklist#341]
Should tenant’s address be only allowed to enter in MA?
Two kinds of addresses: (1) address where they live now and (2) address where the problem is. The “problem” address should be used for locating the court and must be in MA. We should let them supply a second address where they currently live and want to appear on court forms

**Comment by miabonardi** [comment]
#326

**Comment by nonprofittechy** [comment]
Started working on this in c6ab46c
