### ISSUE TITLE
Is there a concept missing in this explanation?

### ISSUE THREAD

**Issue by CaroRob** [LemmaLegalConsulting/docassemble-HousingCodeChecklist#398]
housing_code_interview.yml

how_far_back_should_i_go_template

subject: |
  What problems should I list?
content: |
  If you want to sue your landlord for money, you can list any problems that you have
  had over the last 6 years. Even if the problem is fixed now. 

> Tenants who do not want to sue their landlord usually only list problems that still 
>   need to be fixed.
  
  Is this Tenants who not want to sue their landlord **for money** or who do not want to sue their landlord at all? Does this mean they just want to write a letter to ask the landlord to fix the repairs, or they want the housing inspector to do something or... who are these tenants and what do they want?

**Comment by nonprofittechy** [comment]
The idea I'm trying to convey is that if someone is only suing to get repairs made, there's no reason to list problems that are already fixed. But they can get money damages for any problem up to 6 years in the past even if it is fixed now.
