### ISSUE TITLE
If you say "none of the above" on simple conditions page, you should go right into exploring more problems

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-HousingCodeChecklist#406]
Currently you get an intermediate screen that says "you've already told us about these problems" but the list of problems is empty.

We should change so it skips this screen or make the language conditional.

**Comment by nonprofittechy** [comment]
Apparently we are checking for the length of a list of elements, but it's not the right list. There may be a method of the class we should be calling instead that gets just the selected conditions.

**Comment by miabonardi** [comment]
Another screen where if user proceeds with selecting no repair issues is funky
![Screen Shot 2023-08-01 at 4 02 03 PM](https://github.com/LemmaLegalConsulting/docassemble-HousingCodeChecklist/assets/65858862/42781531-ffd8-4d02-891d-fe7ec850d9d6)

**Comment by miabonardi** [comment]
![Screen Shot 2023-08-01 at 4 20 51 PM](https://github.com/LemmaLegalConsulting/docassemble-HousingCodeChecklist/assets/65858862/30c7c4ec-7f54-4463-bacb-8f93a214955f)

Skip and continue button doesnt work unless you add at least 1 problem

**Comment by miabonardi** [comment]
Tried this for id: review simple conditions

len(kind_of_lawsuit.true_values()) > 0 or bad_conditions.count_conditions() > 0
