### ISSUE TITLE
Add an overall review screen, remove some of the edit links on the navigation

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-HousingCodeChecklist#409]
On the preview_docs page, don't reference "click on the left" instead have a button to get to the review screen.

**Comment by miabonardi** [comment]
https://github.com/LemmaLegalConsulting/docassemble-HousingCodeChecklist/blob/44b2531af7d8e1dc28bf93cdf88c10732f3aa2b4/docassemble/HousingCodeChecklist/data/questions/housing_code_interview.yml#L1456
