### ISSUE TITLE
Should we offer warnings when people add conditions that are very old?

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-HousingCodeChecklist#412]
Maybe also include in the prompt "enter the date it was fixed within the last 6 years. if it was fixed before 6 years before today (show the specific date 6 years ago), don't list it."

Also on the screen "check the problems that were fixed no earlier than (date today minus 6 years)"

**Comment by miabonardi** [comment]
![Screen Shot 2023-07-31 at 4 41 58 PM](https://github.com/LemmaLegalConsulting/docassemble-HousingCodeChecklist/assets/65858862/349498fe-608e-4125-9905-30d3ec8924b4)

This instruction seems contradictory

**Comment by miabonardi** [comment]
Is there a 6 year SoL on reporting any problem, even if it still isn't fixed? Or is the SoL on suing for problems that have been fixed within the last 6 years?

**Comment by nonprofittechy** [comment]
Yes fixed is doing some extra work there, could be clarified.

SoL is for when you were experiencing the problem, so if it wasn't fixed
until 5.9 years ago it can still be claimed.
