### ISSUE TITLE
Contempt complaint not always populating

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-HousingCodeChecklist#419]
Contempt complaint will only populate if `has_tro` is `True`

Should we only allow the user to continue to make a contempt complaint if `has_tro` is `True`? 

If not and we want users to proceed even if `has_tro` is `False`, it will not ask the contempt complaint questions and will only add parties names to complaint and will be incomplete on download. 

https://github.com/LemmaLegalConsulting/docassemble-HousingCodeChecklist/blob/44b2531af7d8e1dc28bf93cdf88c10732f3aa2b4/docassemble/HousingCodeChecklist/data/questions/orders_and_contempt_complaint.yml#L15-L21

**Comment by nonprofittechy** [comment]
Yes, you cannot file for contempt unless you have an equitable order in place.

**Comment by miabonardi** [comment]
@nonprofittechy also if user answers "No" on this screen, contempt complaint shows on download but doesn't populate anything. Should we have it go to a kickout (seems like a ways into the interview for kickout)? Redirect to explore more conditions? What is the best flow? (I see the two "did" typo)

<img width="682" alt="262512515-d8daaeba-df87-4c8f-86aa-984141fc96e7" src="https://github.com/LemmaLegalConsulting/docassemble-HousingCodeChecklist/assets/65858862/ef374c62-84b2-419a-ab1d-8c9b5cab75be">
