### ISSUE TITLE
confusing language on `main_triage_screen`

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-HousingCodeChecklist#429]
Is this language correct "You shouldn't start a new court case with UpToCode." ? 

https://github.com/LemmaLegalConsulting/docassemble-HousingCodeChecklist/blob/f9dae1abdce0e65530684f78dee86c06c65eafcd/docassemble/HousingCodeChecklist/data/questions/housing_code_interview.yml#L1245C56-L1245C56

**Comment by miabonardi** [comment]
"If you have an active eviction case, you shouldn't start a new court case with UpToCode." ?

**Comment by nonprofittechy** [comment]
This only appears if they answer "yes" to having an active eviction case, so I think it's clear enough. Were you seeing it in that context?

**Comment by miabonardi** [comment]
Yes but still found it confusing
