### ISSUE TITLE
Readability - "Explore" is such a literary verb and more conceptual than concrete so edited with more concrete verbs

### ISSUE THREAD

**Issue by CaroRob** [LemmaLegalConsulting/docassemble-HousingCodeChecklist#447]
I am not sure tenants want to explore the problems they have with their housing  - they can explore solutions, but more graphic verbs are to look at, find, get also slightly easier to read. 

So I made a branch in which I substituted this verb with more specific, concrete, literal verbs.

**Comment by KelizaMcGuire** [comment]
This issue was solved with the merge of #448
