### ISSUE TITLE
Readability - retaliation explanation needs larger yellow box

### ISSUE THREAD

**Issue by CaroRob** [LemmaLegalConsulting/docassemble-HousingCodeChecklist#449]
I expanded the explanation of retaliation because it is helpful to have a clearer explanation if lengthier explantion in UpToCode rather than having to go to MassLegalHelp, but also added separate links to retalion by raising rent v. retalation by evicting a tenant - it is difficult to find this information on MLH and tenants who are experiencing one form of retaliation may not be able to find the info on MLH for the other from just one web page.

Because this info on UpToCode is lengthier it needs more room and I could not figure out how to expand the yellow box to encompass more text despite the fact that one of [the first screens in the interview](https://github.com/LemmaLegalConsulting/docassemble-HousingCodeChecklist/blob/bdc31117ccaae9b18886fc9e8157a1504a38acc0/docassemble/HousingCodeChecklist/data/questions/housing_code_interview.yml#L455) does have a larger yellow box.

I also gave that screen an id: "How UpToCode works"

**Comment by KelizaMcGuire** [comment]
The yellow retaliation box has been expanded to avoid the need for users to scroll.
