### ISSUE TITLE
Update website

### ISSUE THREAD

**Issue by KelizaMcGuire** [LemmaLegalConsulting/docassemble-HousingCodeChecklist#472]
Improve the layout and provide clear instructions on what the tool is for and how to use it.

<img width="1313" alt="Screenshot 2024-08-08 at 1 48 33 PM" src="https://github.com/user-attachments/assets/23c8f200-bab1-4b61-bea4-e39f77f79283">
<img width="1308" alt="Screenshot 2024-08-08 at 1 48 41 PM" src="https://github.com/user-attachments/assets/33de5861-6646-4739-9c4f-cd0d5692fe40">
<img width="1316" alt="Screenshot 2024-08-08 at 1 48 52 PM" src="https://github.com/user-attachments/assets/2a5ff017-e322-41d4-89b3-f3a6977f3f49">
<img width="1316" alt="Screenshot 2024-08-08 at 1 49 27 PM" src="https://github.com/user-attachments/assets/89e89c69-807e-431b-be8e-377029740053">

**Comment by ll-jgraszer** [comment]
I've relaunched the homepage for https://getuptocode.org/ with these updates. Also I've added the partnership logos below the text for branding and recognition below the text part too.
