### ISSUE TITLE
Not redirected to interview when log back in

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-HousingCodeChecklist#56]
&nbsp; | &nbsp;
-------|------------------------------------
Page title | Log in
Steps to reproduce | I got logged out of my account so I tried to log back in using my phone.
Expected behavior | I got sent a verification code and put it in. I expected to be logged back in.
What happened instead | I got a screen that said "File not found" and could not return to my interview.
Other information | 
Maturity target | Level 2 - this needs to be fixed to meet expectations of a basic intake
Tester contact info | Allie MLRI

**Comment by miabonardi** [comment]
config issue, test again, check with Jonathan if still not working

**Comment by miabonardi** [comment]
Worked when I tested it on mobile
